In [4]:
from processing import convert_command_file1
num_files = 100_000
data_dir = "../Data3"
C = [convert_command_file1(data_dir + "/commands/command_" + str(i)) for i in range(num_files)]


In [17]:
import numpy as np
C = np.array(C)

In [20]:
C.shape

(200000, 11)

In [19]:
C = C.reshape(-1,11)

In [23]:
C.max(axis=0)

array([1.0000000e+00, 8.9999771e-01, 6.0000000e+02, 1.0000000e+04,
       1.0000000e+02, 9.9999845e-01, 9.9999559e-01, 9.9999957e-02,
       0.0000000e+00, 9.9999142e-01, 4.9998045e-02], dtype=float32)

In [24]:
C.min(axis=0)

array([ 1.0000000e+00,  1.0000468e-01,  1.0000000e+02,  1.0000000e+04,
        1.0000000e+02,  1.1855740e-05,  1.0021703e-05,  1.0000621e-02,
        0.0000000e+00,  4.8768070e-06, -4.9994953e-02], dtype=float32)

In [25]:
C.mean(axis=0)

array([1.0000000e+00, 4.9983308e-01, 3.4965735e+02, 9.9861475e+03,
       1.0000000e+02, 5.0080639e-01, 4.9980393e-01, 5.4900099e-02,
       0.0000000e+00, 4.9817774e-01, 2.1722447e-04], dtype=float32)